apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-regional-lb-http-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Regional HTTP Load Balancer Terraform Module
    source:
      repo: https://github.com/googlestaging/terraform-google-regional-lb-http.git
      sourceType: git
  ui:
    input:
      variables:
        backend_service_name:
          name: backend_service_name
          title: Backend Service Name
        forwarding_rule_name:
          name: forwarding_rule_name
          title: Forwarding Rule Name
        name:
          name: name
          title: Name
        proxy_name:
          name: proxy_name
          title: Proxy Name
        region:
          name: region
          title: Region
        url_map:
          name: url_map
          title: Url Map
        url_map_name:
          name: url_map_name
          title: Url Map Name
