apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-regional-lb-http
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Regional HTTP Load Balancer Terraform Module
    source:
      repo: https://github.com/googlestaging/terraform-google-regional-lb-http.git
      sourceType: git
    description: {}
  content:
    subBlueprints:
      - name: backend
        location: modules/backend
      - name: frontend
        location: modules/frontend
    examples:
      - name: test-regional-lb
        location: examples/test-regional-lb
  interfaces:
    variables:
      - name: backend_service_name
        description: The name of the backend service
        varType: string
        required: true
      - name: region
        description: The region where the load balancer will be created
        varType: string
        defaultValue: us-central1
      - name: url_map_name
        description: The name of the URL map
        varType: string
        required: true
      - name: proxy_name
        description: The name of the HTTP proxy
        varType: string
        required: true
      - name: forwarding_rule_name
        description: The name of the forwarding rule
        varType: string
        required: true
    outputs:
      - name: backend_service_name
        description: The name of the backend service
      - name: forwarding_rule_ip
        description: The IP address of the forwarding rule
      - name: proxy_name
        description: The name of the HTTP proxy
      - name: url_map_name
        description: The name of the URL map
